version: "3.9"

services:
  db:
    image: postgres:15
    container_name: taxiMonitor_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2008
      POSTGRES_DB: taxiMonitor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: taxiMonitor_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - uploads_data:/app/core/uploads
    command: >
      sh -c "
        npx prisma@6 generate &&
        npx prisma@6 migrate deploy &&
        npm run start:prod
      "
    environment:
      DATABASE_URL: postgresql://postgres:2008@db:5432/taxiMonitor_db

volumes:
  postgres_data:
  uploads_data:
